[package]
name = "hand"
version = "0.1.0"
edition = "2021"

[dependencies]
lexer = { path = "../lexer" }
parser = { path = "../parser" }
ual = { path = "../ual" }
ual-derive = { path = "../ual-derive" }