[package]
name = "hand"
version = "0.1.0"
edition = "2021"

[dependencies]
lexer = { path = "../lexer" }
parser = { path = "../parser" }
cir = { path = "../cir" }

thiserror = "1.0"
codespan-reporting = { version = "0.11" }
