[package]
name = "encode-proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = { version = "2.0.76", features = ["full"] }
proc-macro-error2 = "2.0.1"
proc-macro-crate = "3.2.0"
