[package]
name = "enc"
version = "0.1.0"
edition = "2021"

[dependencies]
hand = { path = "../hand" }
matcher = { path = "../matcher" }
cir = { path = "../cir" }
encode-proc = { path = "../encode-proc", optional = true }

byteorder = "1.5.0"

[dev-dependencies]

[features]
macros = ["encode-proc"]