[package]
name = "ual"
version = "0.1.0"
edition = "2021"

[dependencies]
lexer = { path = "../lexer" }
parser = { path = "../parser" }
intern = { path = "../intern" }
thiserror = "1.0"
miette = "7.2"