[instruction.adc]
name = "Add with Carry"

[[instruction.adc.variant]]
title = "ADC, ADCS (immediate)"
description = """
Add with Carry (immediate) adds an immediate value and the Carry flag value to a register value, and writes the 
result to the destination register.
"""
syntax = "ADC{S}{<c>} {<Rd>,} <Rn>, #<const>"
encoding = "[c:4][0 0 1 0][1 0 1][S][Rn:4][Rd:4][const:12]"

[[instruction.adc.variant]]
title = "ADC, ADCS (register)"
description = """
Add with Carry (register) adds a register value, the Carry flag value, and an optionally-shifted register value, and 
writes the result to the destination register.
"""
syntax = [
    "ADC{S}{<c>} {<Rd>,} <Rn>, <Rm>, RRX",
    "ADC{S}{<c>} {<Rd>,} <Rn>, <Rm> {, <shift> #<amount>}"
]
encoding = "[c:4][0 0 0 0][1 0 1][S][Rn:4][Rd:4][amount:5][stype:2][0][Rm:4]"